//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servis
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BazePodataka2ModelContainer : DbContext
    {
        public BazePodataka2ModelContainer()
            : base("name=BazePodataka2ModelContainer")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Obavestenje> Obavestenja { get; set; }
        public virtual DbSet<Korisnik> Korisnici { get; set; }
        public virtual DbSet<Prima> PrimljenaObavestenja { get; set; }
        public virtual DbSet<Kurs> Kursevi { get; set; }
        public virtual DbSet<NastavnaTema> NastavneTeme { get; set; }
        public virtual DbSet<Prijavljen> Prijavljeni { get; set; }
        public virtual DbSet<Test> Testovi { get; set; }
        public virtual DbSet<Pitanje> Pitanja { get; set; }
        public virtual DbSet<Odgovor> Odgovori { get; set; }
        public virtual DbSet<Sadrzi> Sadrzis { get; set; }
        public virtual DbSet<Polaze> Polazes { get; set; }
        public virtual DbSet<Sastoji> Sastojis { get; set; }
        public virtual DbSet<Poseduje> Posedujes { get; set; }

        public virtual DbSet<Ucenik> Korisnici_Ucenik { get; set; }
        public virtual DbSet<Nastavnik> Korisnici_Nastavnik { get; set; }
    }
}
