//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Obavestenje
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Obavestenje()
        {
            this.Primas = new HashSet<Prima>();
        }
    
        public int IdObavestenja { get; set; }
        public string Naslov { get; set; }
        public string Tekst { get; set; }
        public System.DateTime DatumSlanja { get; set; }
        public int KorisnikIdKorisnika { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Prima> Primas { get; set; }
        public virtual Korisnik Korisnik { get; set; }
    }
}
