//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Prima
    {
        public int ObavestenjeIdObavestenja { get; set; }
        public int KorisnikIdKorisnika { get; set; }
        public System.DateTime DatumCitanja { get; set; }
        public bool Obrisano { get; set; }
    
        public virtual Korisnik Korisnik { get; set; }
        public virtual Obavestenje Obavestenje { get; set; }
    }
}
