//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Servis
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sadrzi
    {
        public int KursIdKursa { get; set; }
        public int NastavnaTemaIdTeme { get; set; }
    
        public virtual Kurs Kurs { get; set; }
        public virtual NastavnaTema NastavnaTema { get; set; }
    }
}
